=== iqrf/iqrf-gateway-frontend/api_http/config-response-1-0-0.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "self": {
        "vendor": "com.iqrftech.self-desc",
        "name": "vonfig-response",
        "format": "jsonschema",
        "version": "1-0-0"
    },
    "type": "object",
    "properties": {
        "applicationName": {
            "type": "string",
            "default": ""
        },
        "resourceDir": {
            "type": "string",
            "default": ""
        },
        "dataDir": {
            "type": "string",
            "default": ""
        },
        "cacheDir": {
            "type": "string",
            "default": ""
        },
        "userDir": {
            "type": "string",
            "default": ""
        },
        "configurationDir": {
            "type": "string",
            "default": ""
        },
        "deploymentDir": {
            "type": "string",
            "default": ""
        },
        "components": {
            "type": "array",
            "items": {
                "$ref": "D:/IqrfWebApp/iqrf-gateway-webapp-frontend/json_definitions/api-http-defs-schema-1-0-0.json#/definitions/configuration"
            }
        }
    },
    "required": [
        "applicationName",
        "resourceDir",
        "dataDir",
        "cacheDir",
        "userDir",
        "configurationDir",
        "deploymentDir",
        "components"
    ]
}

=== iqrf/iqrf-gateway-frontend/src/api_http_data/config-response-1-0-0-example.json
{
  "applicationName": "",
  "resourceDir": "",
  "dataDir": "",
  "cacheDir": "",
  "userDir": "",
  "configurationDir": "",
  "deploymentDir": "",
  "components": [
    {
      "name": "",
      "libraryPath": "",
      "libraryName": "",
      "enabled": false,
      "startlevel": 0
    },
    {
      "name": "",
      "libraryPath": "",
      "libraryName": "",
      "enabled": false,
      "startlevel": 0
    },
    {
      "name": "",
      "libraryPath": "",
      "libraryName": "",
      "enabled": false,
      "startlevel": 0
    },
    {
      "name": "",
      "libraryPath": "",
      "libraryName": "",
      "enabled": false,
      "startlevel": 0
    }
  ]
}
